// Scans public/products/** and writes src/data/photoManifest.js.
// Run:  node scripts/build_photo_manifest.js   (add to package.json "prebuild")
import { readdirSync, statSync, writeFileSync } from "fs";
import { join } from "path";
const ROOT = "public/products";
const out = {};
function walk(dir, prefix = "") {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, prefix ? `${prefix}/${name}` : name);
    else if (/\.(jpe?g|png|webp)$/i.test(name) && !name.startsWith("_"))
      out[prefix ? `${prefix}/${name}` : name] = true;
  }
}
try { walk(ROOT); } catch { /* folder may not exist yet */ }
writeFileSync(
  "src/data/photoManifest.js",
  "// AUTO-GENERATED by scripts/build_photo_manifest.js — do not edit.\nexport default " +
    JSON.stringify(out, null, 2) + ";\n"
);
console.log(`photoManifest: ${Object.keys(out).length} images`);
